language: python
python:
    - "2.7"

install:
    - pip install -r src/requirements.txt
    - pip install -r test_requirements.txt
    - pip install coveralls

script:
    - nosetests --with-coverage --cover-package=src tests

after_success:
    - coveralls