language: python
python:
- '2.7'
env:
  - TEST_DIR=package
  - TEST_DIR=.

install:
    - pip install coveralls
    - pushd package
    - 'if [ ${TRAVIS_BRANCH} \!= "master" ] && [ -f dev_requirements.txt ]; then
        pip install --extra-index-url https://testpypi.python.org/pypi -r dev_requirements.txt;
        python setup.py develop --no-deps;
      else
        python setup.py install;
      fi'
    - popd
    - 'if [ $TEST_DIR = "package" ]; then
          cd $TEST_DIR;
      fi'
    - pip install -r test_requirements.txt

script:
    - 'if [ $TEST_DIR = "package" ]; then
        nosetests --with-coverage --cover-package=cloudshell.firewall.juniper.junos tests;
      else
        nosetests --with-coverage --cover-package=src tests;
      fi'

after_success:
    - coveralls